import Head from "next/head";
import Button from "../src/components/Button";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import PageLayout from "../src/components/PageLayout";

export default function Home() {
  return (
    <>
      <Head>
        <title>WatchPoint</title>
        <meta name="landing Page" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageLayout>
        <div className="w-full flex flex-col items-center">
          <h1 className="mt-2 text-h2-mobile sm:text-h2-small md:text-h2-medium lg:text-h2-large">
            WatchPoint
          </h1>

          <Image
            className={styles.logo}
            src="/images/Watchpoint-logo.png"
            height={128}
            width={128}
            alt="Logo"
          ></Image>

          <h2>The All - in - One</h2>
          <h2>Health & Fitness Lifestyle Tracker </h2>

          <Button path="/about" label="About WatchPoint" />
          <Button path="/createAccount" label="Create Account" />
          <Button path="/signIn" label="Sign In" />

          {/* <Button
          onClick={() => {
            alert("Hello");
          }}
          label="Hello button" */}
          {/* /> */}
        </div>
      </PageLayout>
    </>
  );
}
